apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  nameSpace: chat-app

spec:
  replicas: 1
  selector:
   matchLabels:
     app: frontend

  templates:
    metadata:
      name: frontend-pod
      nameSpace: chat-app
      labels:
       app: frontend

    spec:
      containers:
        - name: chatapp-frontend
          image: nikunj07/chatapp-frontend:latest
          ports:
            - containerPort: 80 
          
          env:
            - name: NODE_ENV
              value: production

