apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  nameSpace: chat-app
spec:
  capacity:
    storage: 5  Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow

